alter table ability drop foreign key FKf8jw2lqr1d1tio88xrxnw64qk;
alter table agent drop foreign key FK62bop6ygdgye7vrdbyudlcjr;
alter table callout drop foreign key FKdlm8bnp6dpu7emes3nx1c3ni2;
drop table if exists ability;
drop table if exists agent;
drop table if exists callout;
drop table if exists callout_seq;
drop table if exists map;
drop table if exists map_seq;
drop table if exists role;
alter table ability drop foreign key FKf8jw2lqr1d1tio88xrxnw64qk;
alter table agent drop foreign key FK62bop6ygdgye7vrdbyudlcjr;
alter table callout drop foreign key FKdlm8bnp6dpu7emes3nx1c3ni2;
drop table if exists ability;
drop table if exists agent;
drop table if exists callout;
drop table if exists callout_seq;
drop table if exists map;
drop table if exists map_seq;
drop table if exists role;
alter table ability drop foreign key FKf8jw2lqr1d1tio88xrxnw64qk;
alter table agent drop foreign key FK62bop6ygdgye7vrdbyudlcjr;
alter table callout drop foreign key FKdlm8bnp6dpu7emes3nx1c3ni2;
drop table if exists ability;
drop table if exists agent;
drop table if exists callout;
drop table if exists callout_seq;
drop table if exists map;
drop table if exists map_seq;
drop table if exists role;
alter table ability drop foreign key FKf8jw2lqr1d1tio88xrxnw64qk;
alter table agent drop foreign key FK62bop6ygdgye7vrdbyudlcjr;
alter table callout drop foreign key FKdlm8bnp6dpu7emes3nx1c3ni2;
drop table if exists ability;
drop table if exists agent;
drop table if exists callout;
drop table if exists callout_seq;
drop table if exists map;
drop table if exists map_seq;
drop table if exists role;
alter table ability drop foreign key FKf8jw2lqr1d1tio88xrxnw64qk;
alter table agent drop foreign key FK62bop6ygdgye7vrdbyudlcjr;
alter table callout drop foreign key FKdlm8bnp6dpu7emes3nx1c3ni2;
drop table if exists ability;
drop table if exists agent;
drop table if exists callout;
drop table if exists callout_seq;
drop table if exists map;
drop table if exists map_seq;
drop table if exists role;
alter table ability drop foreign key FKf8jw2lqr1d1tio88xrxnw64qk;
alter table agent drop foreign key FK62bop6ygdgye7vrdbyudlcjr;
alter table callout drop foreign key FKdlm8bnp6dpu7emes3nx1c3ni2;
drop table if exists ability;
drop table if exists agent;
drop table if exists callout;
drop table if exists callout_seq;
drop table if exists map;
drop table if exists map_seq;
drop table if exists role;
alter table ability drop foreign key FKf8jw2lqr1d1tio88xrxnw64qk;
alter table agent drop foreign key FK62bop6ygdgye7vrdbyudlcjr;
alter table callout drop foreign key FKdlm8bnp6dpu7emes3nx1c3ni2;
drop table if exists ability;
drop table if exists agent;
drop table if exists callout;
drop table if exists callout_seq;
drop table if exists map;
drop table if exists map_seq;
drop table if exists role;
alter table ability drop foreign key FKbib1sqjy10vnd7440ts6nneg1;
alter table agent drop foreign key FK7txk3lmpvnkj2kowlfsypxuba;
alter table callout drop foreign key FKglqakj9psh4xgxep34xrv7bli;
drop table if exists ability;
drop table if exists agent;
drop table if exists callout;
drop table if exists callout_seq;
drop table if exists map;
drop table if exists role;
alter table ability drop foreign key FKbib1sqjy10vnd7440ts6nneg1;
alter table agent drop foreign key FK7txk3lmpvnkj2kowlfsypxuba;
alter table callout drop foreign key FKglqakj9psh4xgxep34xrv7bli;
drop table if exists ability;
drop table if exists agent;
drop table if exists callout;
drop table if exists callout_seq;
drop table if exists map;
drop table if exists role;
alter table ability drop foreign key FKbib1sqjy10vnd7440ts6nneg1;
alter table agent drop foreign key FK7txk3lmpvnkj2kowlfsypxuba;
alter table callout drop foreign key FKglqakj9psh4xgxep34xrv7bli;
drop table if exists ability;
drop table if exists agent;
drop table if exists callout;
drop table if exists callout_seq;
drop table if exists map;
drop table if exists role;
alter table ability drop foreign key FKbib1sqjy10vnd7440ts6nneg1;
alter table agent drop foreign key FK7txk3lmpvnkj2kowlfsypxuba;
alter table callout drop foreign key FKglqakj9psh4xgxep34xrv7bli;
drop table if exists ability;
drop table if exists agent;
drop table if exists callout;
drop table if exists callout_seq;
drop table if exists map;
drop table if exists role;
alter table ability drop foreign key FKbib1sqjy10vnd7440ts6nneg1;
alter table agent drop foreign key FK7txk3lmpvnkj2kowlfsypxuba;
alter table callout drop foreign key FKglqakj9psh4xgxep34xrv7bli;
drop table if exists ability;
drop table if exists agent;
drop table if exists callout;
drop table if exists callout_seq;
drop table if exists map;
drop table if exists role;
alter table ability drop foreign key FKbib1sqjy10vnd7440ts6nneg1;
alter table agent drop foreign key FK7txk3lmpvnkj2kowlfsypxuba;
alter table callout drop foreign key FKglqakj9psh4xgxep34xrv7bli;
drop table if exists ability;
drop table if exists agent;
drop table if exists callout;
drop table if exists map;
drop table if exists role;
alter table ability drop foreign key FKbib1sqjy10vnd7440ts6nneg1;
alter table agent drop foreign key FK7txk3lmpvnkj2kowlfsypxuba;
alter table callout drop foreign key FKglqakj9psh4xgxep34xrv7bli;
drop table if exists ability;
drop table if exists agent;
drop table if exists callout;
drop table if exists map;
drop table if exists role;
alter table ability drop foreign key FKbib1sqjy10vnd7440ts6nneg1;
alter table agent drop foreign key FK7txk3lmpvnkj2kowlfsypxuba;
alter table callout drop foreign key FKglqakj9psh4xgxep34xrv7bli;
drop table if exists ability;
drop table if exists agent;
drop table if exists callout;
drop table if exists map;
drop table if exists role;
